AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2 AMI
  (ami-0bef6cc322bfff646) EC2 Instance with custom security group
  allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github
  repository, then installed on Flask.
Parameters:
  KeyName:
    Description: Choose your Key Pair for SSH connections.
    Type: AWS::EC2::KeyPair::KeyName 

Resources:
  WebServerSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH ports # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0bef6cc322bfff646" #amazon2
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref WebServerSecGrp
      Tags: 
        - Key:  Name
          Value:  !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
          #!/bin/bash
          yum update -y 
          yum install python3
          pip3 install flask
          cd /home/ec2-user
          FOLDER="https://raw.githubusercontent.com/efendicagli/my-flask-projects/main/Project-001-Roman-Numerals-Converter"
          wget ${FOLDER}/app.py
          mkdir templates && cd templates
          wget ${FOLDER}/templates/index.html
          wget ${FOLDER}/templates/result.html
          cd ..
          python3 app.py

Outputs:
  WebSiteURL: 
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServer.PublicDnsName